before:
  hooks:
    - go mod download
builds:
- env:
  - CGO_ENABLED=0
archives:
- replacements:
    darwin: Darwin
    linux: Linux
    windows: Windows
    386: i386
    amd64: x86_64
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'

release:
  github:
    owner: shellbear
    name: faktur

dockers:
  -
    binaries:
    - faktur
    dockerfile: Dockerfile.cgo
    image_templates:
    - "docker.pkg.github.com/shellbear/faktur/faktur:{{ .Tag }}"
    - "docker.pkg.github.com/shellbear/faktur/faktur:latest"
    build_flag_templates:
    - "--pull"
    - "--label=org.opencontainers.image.created={{.Date}}"
    - "--label=org.opencontainers.image.name={{.ProjectName}}"
    - "--label=org.opencontainers.image.revision={{.FullCommit}}"
    - "--label=org.opencontainers.image.version={{.Version}}"

